### ISSUE TITLE
notice of possibly missing dependency

### ISSUE THREAD

**Issue by kgilmer** [xeome/compix#1]
Hi, I like your project!  I'm playing around with making a [debian package for it](https://github.com/regolith-linux/regolith-compix/tree/debian) (may show up here eventually: https://github.com/regolith-linux/voulage) and noticed that the makefile uses the command `cppcheck`.  This is provided by the `cppcheck` package on Ubuntu, and would need to be listed as a dependency for other packagers I would guess.

If there is a way I can get notified if you do a formal release, I would like to do that so that my package may remain up to date.

**Comment by xeome** [comment]
Hello, I should clarify a few things first, I'm a very inexperienced and unprofessional C programmer, I found this project called axcomp while searching around Github for X compositors, it didn't have a readme or building instructions, and it hadn't had a commit since 2020 January, so I took it and fixed some crashes, added a readme, and brought attention to it. However, I was unable to find a way to contact the original creator of axcomp, so there's that.
Regarding the cppcheck dependency, I will add it to the readme right away; thank you for informing me; I didn't even notice it on the makefile.
As for the formal release, I don't intend to make one just yet. I don't think it's ready for a release, and I won't be able to work on it until I learn more C. You can reach me via Discord (if you use it). 
My Discord contact information is as follows: jomo#4353
I'm not sure how else you'd contact me, but you can tell me whatever service you're most comfortable with to communicate with me.

**Comment by kgilmer** [comment]
Hi @xeome!

> As for the formal release, I don't intend to make one just yet. I don't think it's ready for a release, and I won't be able to work on it until I learn more C. 

I totally understand.  I have a fork of your repo that also includes the debian files needed to generate debian packages.  If/when you are ready for a release just let me know and I'll update my repo and make the package.  If you never get to it, no worries :smile: 

I'll close the issue now as I've noticed you added the `cppcheck` dependency to the readme.
